name: morshd
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  awesome_dialog: ^3.2.1
  build_runner: ^2.4.15
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  dash_chat_2: ^0.0.21
  dio: ^5.7.0
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gemini: ^3.0.0
  flutter_markdown: ^0.7.5
  flutter_native_splash: ^2.4.1
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.4.9
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.8.0
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  geolocator: ^13.0.2
  get_it: ^8.0.3
  google_generative_ai: ^0.4.6
  google_maps_flutter: ^2.12.3
  google_place: ^0.4.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  http_parser: ^4.1.2
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  lottie: ^3.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pinput: ^5.0.1
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  video_player: ^2.10.0
  image: ^4.1.7
  rive:  
  fvp:

dependency_overrides:
  http: ^1.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
